##### defaults

baseURL = "https://saharjahanikia.github.io"
languageCode = "en-us"
title = "Sahar Jahanikia - Florals and events"
theme = "liva"
publishDir = "../saharjahanikia.github.io"
enableGitInfo = true
summaryLength = "10"
paginate = 6
[outputs]
  home = ["HTML", "AMP", "RSS", "JSON"]

######################## Plugins
[params.plugins]
  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"

### Navigation

[menu]
	[[menu.main]]
  name = "About"
  URL = "about/about"
  weight = 2

  [[menu.main]]
  name = "Florals"
  URL = "floral"
  weight = 3

  [[menu.main]]
  name = "Events"
  URL = "event"
  weight = 4

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 5

  [[menu.footer]]
  name = "Florals"
  URL = "floral"
  weight = 3

  [[menu.footer]]
  name = "Events"
  URL = "event"
  weight = 4
  
  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 5


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "Sahar Jahanikia, Floral & Events"
author = "Sahar Jahanikia"
# Google Analitycs
#googleAnalitycsID = "Your ID"
# Contact Information
mobile = "408-429-xxxx"
email = "info@cafechampu.com"
location = "Palo Alto, California"
# copyright
copyright = "| @2020 [Sahar Jahanikia](http://cafechampu.com) All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook"
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt"
link = "#"

[[params.social]]
title = "instagram"
icon = "ti-instagram"
link = "#"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin"
link = "#"
